import type { Metadata } from "next";
import localFont from "next/font/local";
import Navigation from "../components/Navigation";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const links = [
  { title: 'Home', href: '/'},
  { title: 'About', href: '/about'},
  { title: 'Contact', href: '/contact'},
  { title: 'Store', href: '/store'},
]

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navigation items={links}/>
        {children}
      </body>
    </html>
  );
}
